/*
 * order.cc
 *
 * Date:    30. 11. 2021
 * Authors: Filip Solich <xsolic00@stud.fit.vutbr.cz>
 *          Marek Sechra <xsechr00@stud.fit.vutbr.cz>
 */

#include <simlib.h>

#include "car_returns.hh"
#include "config.hh"
#include "order.hh"
#include "stats.hh"


Order::Order(Facility *fac, Store *cars):
	fac(fac), cars(cars)
{};

void Order::Behavior()
{
	// Order should not exist because was generated by "inactive" generator.
	if (fac->Busy()) return;

	int sum = 0;

	if (cars->Full()) wait_for_car_count++;

	// Order takes one car from store.
	double wait_time = Time;
	Enter(*cars);
	wait_time = Time - wait_time;

	error:
	// Order delivery.
	int x = Exponential(ORDER_DELIVERY_TIME);
	sum += x;
	Wait(x);

	// Order failed.
	if(Random() <= DELIVERY_FAILED)
		goto error;

	// Order is picked by customer.
	int y = Exponential(CUSTOMER_TAKE_ORDER);
	Wait(y);
	sum += y;

	delivery_time(sum);
	wait_for_car(wait_time);

	(new CarReturns(cars))->Activate();
}
